spring:
  application:
    name: gainstrack-api
  profiles:
    active: dev # Perfil por defecto — sobreescrito por SPRING_PROFILES_ACTIVE
  threads: # Virtual Threads
    virtual:
      enabled: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:2592000000} # 24 horas en milisegundos