spring:
  application:
    name: gainstrack-api
  profiles:
    active: dev # Perfil por defecto — sobreescrito por SPRING_PROFILES_ACTIVE
  threads: # Virtual Threads
    virtual:
      enabled: true

server:
  port: ${SERVER_PORT:8080} # Se le envía como variable de entorno al momento de levantar el contenedor

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:2592000000} # 24 horas en milisegundos

google:
  client-id: ${GOOGLE_CLIENT_ID}